### ISSUE TITLE
short and sweet!

### ISSUE THREAD

**Issue by 404pnf** [dtinth/itself#1]
The code is short!  The effect is amazing!  Thank you!

**Comment by dtinth** [comment]
Glad that you like it, but may I suggest you to use ES6 arrow functions? Short arrow functions now become standard. It’s now available in most modern browsers.

``` js
// itself
var itself = its = require('itself'), its
var oddTaskNames = tasks
        .filter(its('.number % 2 == 0'))
        .map(its('.name'))
```

ES6

``` js
// arrow function
const oddTaskNames = tasks
        .filter(task => task.number % 2 == 0)
        .map(task => task.name)
```

**Comment by 404pnf** [comment]
Your implementation is short. It opened my eyes.  Using string literals and new Function might be frowned upon but it feels like magic.

Using 'itself' makes the code look more functional. :)
